loading dataframe from

In [ ]:
import pandas as pd

df = pd.read_csv('https://drive.google.com/uc?export=download&id=1k26vJfnpQx-Vl509-pjxhBkWu5efS12s')

In [ ]:
!jupyter nbconvert --execute --to html "/content/Project_Notebook_2_Baseline.ipynb"

[NbConvertApp] Converting notebook /content/Project_Notebook_2_Baseline.ipynb to html
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/jupyter_core/application.py", line 284, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 420, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 487, in export_single_notebook
    output, resources = self.exporter.from_filename(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/templateexporter.py", line 390, in from_filename
    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/templateexporter.py", line 396, in from_file
    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 220, in from_file
    return self.from_notebook_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/html.py", line 286, in from_notebook_node
    html, resources = super().from_notebook_node(nb, resources, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/templateexporter.py", line 412, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 353, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/preprocessors/base.py", line 48, in __call__
    return self.preprocess(nb, resources)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/preprocessors/execute.py", line 103, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/preprocessors/execute.py", line 124, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 678, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1961, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Task exception was never retrieved
future: <Task finished name='Task-53' coro=<NotebookClient.async_execute_cell() done, defined at /usr/local/lib/python3.12/dist-packages/nbclient/client.py:920> exception=CellExecutionError('An error occurred while executing the following cell:\n------------------\nfrom sklearn.ensemble import RandomForestRegressor\n\nrf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)\nrf.fit(X_train_scaled, y_train) #100 is arbitrary for now\n\ny_pred_rf = rf.predict(X_test_scaled)\n\nresults_rf = evaluate(y_test, y_pred_rf, "Random Forest")\n------------------\n\n\n\x1b[0;31m---------------------------------------------------------------------------\x1b[0m\n\x1b[0;31mKeyboardInterrupt\x1b[0m                         Traceback (most recent call last)\n\x1b[0;32m/tmp/ipykernel_46401/2984791240.py\x1b[0m in \x1b[0;36m<cell line: 0>\x1b[0;34m()\x1b[0m\n\x1b[1;32m      2\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m      3\x1b[0m \x1b[0mrf\x1b[0m \x1b[0;34m=\x1b[0m \x1b[0mRandomForestRegressor\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mn_estimators\x1b[0m\x1b[0;34m=\x1b[0m\x1b[0;36m100\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0mrandom_state\x1b[0m\x1b[0;34m=\x1b[0m\x1b[0;36m42\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0mn_jobs\x1b[0m\x1b[0;34m=\x1b[0m\x1b[0;34m-\x1b[0m\x1b[0;36m1\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0;32m----> 4\x1b[0;31m \x1b[0mrf\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mfit\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mX_train_scaled\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0my_train\x1b[0m\x1b[0;34m)\x1b[0m \x1b[0;31m#100 is arbitrary for now\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m      5\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m      6\x1b[0m \x1b[0my_pred_rf\x1b[0m \x1b[0;34m=\x1b[0m \x1b[0mrf\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mpredict\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mX_test_scaled\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\n\x1b[0;32m/usr/local/lib/python3.12/dist-packages/sklearn/base.py\x1b[0m in \x1b[0;36mwrapper\x1b[0;34m(estimator, *args, **kwargs)\x1b[0m\n\x1b[1;32m   1387\x1b[0m                 )\n\x1b[1;32m   1388\x1b[0m             ):\n\x1b[0;32m-> 1389\x1b[0;31m                 \x1b[0;32mreturn\x1b[0m \x1b[0mfit_method\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mestimator\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0;34m*\x1b[0m\x1b[0margs\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0;34m**\x1b[0m\x1b[0mkwargs\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m   1390\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m   1391\x1b[0m         \x1b[0;32mreturn\x1b[0m \x1b[0mwrapper\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\n\x1b[0;32m/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py\x1b[0m in \x1b[0;36mfit\x1b[0;34m(self, X, y, sample_weight)\x1b[0m\n\x1b[1;32m    485\x1b[0m             \x1b[0;31m# parallel_backend contexts set at a higher level,\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m    486\x1b[0m             \x1b[0;31m# since correctness does not rely on using threads.\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0;32m--> 487\x1b[0;31m             trees = Parallel(\n\x1b[0m\x1b[1;32m    488\x1b[0m                 \x1b[0mn_jobs\x1b[0m\x1b[0;34m=\x1b[0m\x1b[0mself\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mn_jobs\x1b[0m\x1b[0;34m,\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m    489\x1b[0m                 \x1b[0mverbose\x1b[0m\x1b[0;34m=\x1b[0m\x1b[0mself\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mverbose\x1b[0m\x1b[0;34m,\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\n\x1b[0;32m/usr/local/lib/python3.12/dist-packages/sklearn/utils/parallel.py\x1b[0m in \x1b[0;36m__call__\x1b[0;34m(self, iterable)\x1b[0m\n\x1b[1;32m     75\x1b[0m             \x1b[0;32mfor\x1b[0m \x1b[0mdelayed_func\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0margs\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0mkwargs\x1b[0m \x1b[0;32min\x1b[0m \x1b[0miterable\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m     76\x1b[0m         )\n\x1b[0;32m---> 77\x1b[0;31m         \x1b[0;32mreturn\x1b[0m \x1b[0msuper\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0m__call__\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0miterable_with_config\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m     78\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m     79\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\n\x1b[0;32m/usr/local/lib/python3.12/dist-packages/joblib/parallel.py\x1b[0m in \x1b[0;36m__call__\x1b[0;34m(self, iterable)\x1b[0m\n\x1b[1;32m   2070\x1b[0m         \x1b[0mnext\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0moutput\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m   2071\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0;32m-> 2072\x1b[0;31m         \x1b[0;32mreturn\x1b[0m \x1b[0moutput\x1b[0m \x1b[0;32mif\x1b[0m \x1b[0mself\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mreturn_generator\x1b[0m \x1b[0;32melse\x1b[0m \x1b[0mlist\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0moutput\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m   2073\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m   2074\x1b[0m     \x1b[0;32mdef\x1b[0m \x1b[0m__repr__\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mself\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m:\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\n\x1b[0;32m/usr/local/lib/python3.12/dist-packages/joblib/parallel.py\x1b[0m in \x1b[0;36m_get_outputs\x1b[0;34m(self, iterator, pre_dispatch)\x1b[0m\n\x1b[1;32m   1680\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m   1681\x1b[0m             \x1b[0;32mwith\x1b[0m \x1b[0mself\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0m_backend\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mretrieval_context\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m:\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0;32m-> 1682\x1b[0;31m                 \x1b[0;32myield\x1b[0m \x1b[0;32mfrom\x1b[0m \x1b[0mself\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0m_retrieve\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m   1683\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m   1684\x1b[0m         \x1b[0;32mexcept\x1b[0m \x1b[0mGeneratorExit\x1b[0m\x1b[0;34m:\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\n\x1b[0;32m/usr/local/lib/python3.12/dist-packages/joblib/parallel.py\x1b[0m in \x1b[0;36m_retrieve\x1b[0;34m(self)\x1b[0m\n\x1b[1;32m   1798\x1b[0m                     \x1b[0mself\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0m_jobs\x1b[0m\x1b[0;34m[\x1b[0m\x1b[0;36m0\x1b[0m\x1b[0;34m]\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mget_status\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mtimeout\x1b[0m\x1b[0;34m=\x1b[0m\x1b[0mself\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mtimeout\x1b[0m\x1b[0;34m)\x1b[0m \x1b[0;34m==\x1b[0m \x1b[0mTASK_PENDING\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m   1799\x1b[0m                 ):\n\x1b[0;32m-> 1800\x1b[0;31m                     \x1b[0mtime\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0msleep\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0;36m0.01\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m   1801\x1b[0m                     \x1b[0;32mcontinue\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m   1802\x1b[0m \x1b[0;34m\x1b[0m\x1b[0m\n\n\x1b[0;31mKeyboardInterrupt\x1b[0m: \n')>
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/jupyter_core/application.py", line 284, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 420, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/nbconvertapp.py", line 487, in export_single_notebook
    output, resources = self.exporter.from_filename(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/templateexporter.py", line 390, in from_filename
    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/templateexporter.py", line 396, in from_file
    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 220, in from_file
    return self.from_notebook_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/html.py", line 286, in from_notebook_node
    html, resources = super().from_notebook_node(nb, resources, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/templateexporter.py", line 412, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/exporters/exporter.py", line 353, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/preprocessors/base.py", line 48, in __call__
    return self.preprocess(nb, resources)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/preprocessors/execute.py", line 103, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.12/dist-packages/nbconvert/preprocessors/execute.py", line 124, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 678, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1961, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.12/dist-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train_scaled, y_train) #100 is arbitrary for now

y_pred_rf = rf.predict(X_test_scaled)

results_rf = evaluate(y_test, y_pred_rf, "Random Forest")
------------------


---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/tmp/ipykernel_46401/2984791240.py in <cell line: 0>()
      2
      3 rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
----> 4 rf.fit(X_train_scaled, y_train) #100 is arbitrary for now
      5
      6 y_pred_rf = rf.predict(X_test_scaled)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py in wrapper(estimator, *args, **kwargs)
   1387                 )
   1388             ):
-> 1389                 return fit_method(estimator, *args, **kwargs)
   1390
   1391         return wrapper

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py in fit(self, X, y, sample_weight)
    485             # parallel_backend contexts set at a higher level,
    486             # since correctness does not rely on using threads.
--> 487             trees = Parallel(
    488                 n_jobs=self.n_jobs,
    489                 verbose=self.verbose,

/usr/local/lib/python3.12/dist-packages/sklearn/utils/parallel.py in __call__(self, iterable)
     75             for delayed_func, args, kwargs in iterable
     76         )
---> 77         return super().__call__(iterable_with_config)
     78
     79

/usr/local/lib/python3.12/dist-packages/joblib/parallel.py in __call__(self, iterable)
   2070         next(output)
   2071
-> 2072         return output if self.return_generator else list(output)
   2073
   2074     def __repr__(self):

/usr/local/lib/python3.12/dist-packages/joblib/parallel.py in _get_outputs(self, iterator, pre_dispatch)
   1680
   1681             with self._backend.retrieval_context():
-> 1682                 yield from self._retrieve()
   1683
   1684         except GeneratorExit:

/usr/local/lib/python3.12/dist-packages/joblib/parallel.py in _retrieve(self)
   1798                     self._jobs[0].get_status(timeout=self.timeout) == TASK_PENDING
   1799                 ):
-> 1800                     time.sleep(0.01)
   1801                     continue
   1802

KeyboardInterrupt:

^C

before we can test our models, we need to build a working pipeline that produces reasonable results.
we picked [Henghes et al. 2021](https://academic.oup.com/mnras/article/505/4/4847/6288434) as our main refrence. since its almost 1-1 with what we are doing in our project. yes its an older paper but its too useful not to use.

they benchmarked 5 of the same ML models we plan to use (LR, kNN, RF, BDT ≈ XGBoost, MLP) on SDSS DR12 with the same 9 features (5 magnitudes + 4 colors).

# setup

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# define features X and target y
# our features are magnitudes + color
# the target is what we are trying to estimate, redshift.
feature_cols = ['u', 'g', 'r', 'i', 'z', 'u_g', 'g_r', 'r_i', 'i_z']
X = df[feature_cols].values
y = df['redshift'].values

print(f"{X.shape}")
print(f"{y.shape}")

(57241, 9)
(57241,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,     # 20% for testing
    random_state=42    # reproducibility
)

print(f"Training set: {X_train.shape[0]} galaxies")
print(f"Test set: {X_test.shape[0]} galaxies")

Training set: 45792 galaxies
Test set: 11449 galaxies

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training mean: {X_train_scaled.mean(axis=0).round(3)}")
print(f"Training std:  {X_train_scaled.std(axis=0).round(3)}")

Training mean: [-0.  0. -0. -0.  0. -0. -0.  0. -0.]
Training std:  [1. 1. 1. 1. 1. 1. 1. 1. 1.]

# Section 1 - Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

print(f"First 5 predictions: {y_pred_lr[:5].round(4)}")
print(f"First 5 true values: {y_test[:5].round(4)}")

First 5 predictions: [0.4785 0.1373 0.1737 0.5747 0.5267]
First 5 true values: [0.5204 0.0382 0.1102 0.5238 0.5556]

reasonable predictions, its fine

###evaluation

our metrics are the following;

- **MAE** (mean absolute error): average of |predicted - actual|. easy to interpret.



---


- **MSE** (mean squared error): punishes large errors.



---


- **bias**: tells us if the model systematically over or under-predicts.


---



- **σ_NMAD**: measures how tightly our predictions cluster around the true values. it's based on the median error instead of the mean, so a handful of bad predictions can't inflate it. lower = more consistent predictions. this is the standard scatter metric in photometric redshift papers.

***Important note.***

  photo-z (photometric redshift) papers don't all use the same formula. Henghes (2021) calls it "Precision" and uses the older Ilbert (2006) definition:
  
`  1.48 × median(|Δz_norm|). `
   
   Treyer (2024) uses the modern statistical NMAD:
   
` 1.48 × median(|Δz_norm - median(Δz_norm)|) `
  
  the same idea but centered around the median first. the numbers differ slightly for biased models.


  we use Henghes's formula since he's our main baseline paper. this lets us compare σ_NMAD directly against their Table 2. we still call it σ_NMAD in our code because that's the name used by most recent papers (Li 2023, Zhou 2024).

---


- **outlier fraction**: the percentage of galaxies where our prediction was very wrong.

    "very wrong" means `|z_predicted - z_actual|/(1 + z_actual) > 0.15`
    
    e.g. predicting z = 0.1 for a galaxy that's actually at z = 0.5.

  ***Important note.***

    same caveat as σ_NMAD: Henghes (2021) uses an older definition

    `(|z_pred - z_spec| > 0.10). `
    
    we use the modern normalized version that matches recent litretuare. since this a bit too outdated, but also there isnt really much of a standard on this anyway
  
   this means we can't directly compare outlier fraction to Henghes, but we can compare to the other 3 papers later on in our paper.

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

def evaluate(y_true, y_pred, model_name):
    # Standard regression metrics
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)

    # Photo-z specific metrics
    dz = (y_pred - y_true) / (1 + y_true)
    bias = np.mean(dz)
    sigma_nmad = 1.48 * np.median(np.abs(dz))
    outlier_fraction = np.mean(np.abs(dz) > 0.15)

    print(f"\n--- {model_name} ---")
    print(f"MAE:              {mae:.4f}")
    print(f"MSE:              {mse:.4f}")
    print(f"Bias:             {bias:.4f}")
    print(f"σ_NMAD:           {sigma_nmad:.4f}")
    print(f"Outlier fraction: {outlier_fraction:.4%}")

    return {'model': model_name, 'MAE': mae, 'MSE': mse,
            'bias': bias, 'sigma_NMAD': sigma_nmad,
            'outlier_fraction': outlier_fraction}

In [ ]:
#compare results
pd.DataFrame({
    'Ours':    [0.0712, 0.0118, 0.0054, 0.0500],
    'Henghes': [0.0509, 0.0057, 0.0397, 0.0434],
}, index=['MAE', 'MSE', 'Bias', 'σ_NMAD']).round(4)

          Ours  Henghes
MAE     0.0712   0.0509
MSE     0.0118   0.0057
Bias    0.0054   0.0397
σ_NMAD  0.0500   0.0434

our LR is worse than Henghes's on MSE/MAE but better on bias.

i think its largely because of the different sample size

since we know the relationship between our features and resshift is non-linear. it might have helped them having a smaller dataset.

what matters here is that we know that LR will preform worst among our models. it doesnt really have to be 1-1 with the paper

# Section 2 - k-Nearest Neighbors

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=10)
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

results_knn = evaluate(y_test, y_pred_knn, "k-Nearest Neighbors")

--- k-Nearest Neighbors ---
MAE:              0.0482
MSE:              0.0080
Bias:             0.0028
σ_NMAD:           0.0274
Outlier fraction: 2.9610%

###evaluation

In [ ]:
pd.DataFrame({
    'Ours':    [0.0482, 0.0080, 0.0028, 0.0276],
    'Henghes': [0.0409, 0.0044, 0.0310, 0.0318],
}, index=['MAE', 'MSE', 'Bias', 'σ_NMAD']).round(4)

          Ours  Henghes
MAE     0.0482   0.0409
MSE     0.0080   0.0044
Bias    0.0028   0.0310
σ_NMAD  0.0276   0.0318

cour MSE is ~2× worse and MAE is slightly worse . this is the same untuned vs tuned gap we saw with LR. Henghes's optimal kNN used k=21 with distance weighting after extensive tuning. we're using k=10 uniform weighting scikit-learn defaults.

but the main baseline goal is met, kNN clearly beats LR  which is the qualitative finding Henghes reports. our pipeline ranks models correctly.

#Section 3 - Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train_scaled, y_train) #100 is arbitrary for now

y_pred_rf = rf.predict(X_test_scaled)

results_rf = evaluate(y_test, y_pred_rf, "Random Forest")

--- Random Forest ---
MAE:              0.0468
MSE:              0.0076
Bias:             0.0019
σ_NMAD:           0.0260
Outlier fraction: 2.9784%

###evaluation

In [ ]:
pd.DataFrame({
    'Ours':    [0.0468, 0.0076, 0.0019, 0.0260],
    'Henghes': [0.0385, 0.0042, 0.0293, 0.0293],
}, index=['MAE', 'MSE', 'Bias', 'σ_NMAD']).round(4)

          Ours  Henghes
MAE     0.0468   0.0385
MSE     0.0076   0.0042
Bias    0.0019   0.0293
σ_NMAD  0.0260   0.0293

### RF results

the same ~2× MSE gap

this is almost certainly still the untuned-vs-tuned story. Henghes's had optimal RF hyperparameters after 1000 iterations of random search. our defaults are obvioully not optimal. proper tuning should close this gap (what we will do later)

what we can note though is that our bias is much better . Henghes's RF  over predicts redshift. idk why, probably one of the hyperparameters

# Section 3 - XGBoost

In [ ]:
from xgboost import XGBRegressor

xgb = XGBRegressor(n_estimators=100, random_state=42, n_jobs=-1)
xgb.fit(X_train_scaled, y_train)

y_pred_xgb = xgb.predict(X_test_scaled)

results_xgb = evaluate(y_test, y_pred_xgb, "XGBoost")

--- XGBoost ---
MAE:              0.0476
MSE:              0.0078
Bias:             0.0019
σ_NMAD:           0.0267
Outlier fraction: 3.0920%

###evaluation

In [ ]:
pd.DataFrame({
    'Ours':    [0.0476, 0.0078, 0.0019, 0.0267],
    'Henghes': [0.0388, 0.0043, 0.0294, 0.0290],
}, index=['MAE', 'MSE', 'Bias', 'σ_NMAD']).round(4)

          Ours  Henghes
MAE     0.0476   0.0388
MSE     0.0078   0.0043
Bias    0.0019   0.0294
σ_NMAD  0.0267   0.0290

XGBoost is the modern version of Henghes's Boosted Decision Tree (BDT). is it a fair comparison?

basically yes, same idea diff implementation

they train data sequentially. but XGBoost is faster and has better regularation. our XGBoost is untuned though so it looks bad anyway.

#Section 4 - MLP

In [ ]:
from sklearn.neural_network import MLPRegressor

mlp = MLPRegressor(random_state=42, max_iter=200)
mlp.fit(X_train_scaled, y_train)

y_pred_mlp = mlp.predict(X_test_scaled)

results_mlp = evaluate(y_test, y_pred_mlp, "Multi-Layer Perceptron")

--- Multi-Layer Perceptron ---
MAE:              0.0503
MSE:              0.0078
Bias:             -0.0006
σ_NMAD:           0.0314
Outlier fraction: 3.0570%

###evaluation

In [ ]:
pd.DataFrame({
    'Ours':    [0.0503, 0.0078, -0.0006, 0.0314],
    'Henghes': [0.0513, 0.0047, 0.0346, 0.0408],
}, index=['MAE', 'MSE', 'Bias', 'σ_NMAD']).round(4)

          Ours  Henghes
MAE     0.0503   0.0513
MSE     0.0078   0.0047
Bias   -0.0006   0.0346
σ_NMAD  0.0314   0.0408

a bit suprised by the results. our single layer defualt MLP preformed on bar with others.

roughly same MSE as our other basline models. better MAE and bias than our ref paper

this is probably because we have more data. but could be also that the ref paper used tnah for activition, the defualt here is ReLU

#Section 6 - Summary

In [ ]:
summary = pd.DataFrame([results_lr, results_knn, results_rf, results_xgb, results_mlp])
summary = summary.set_index('model').round(4)
summary['outlier_fraction'] = (summary['outlier_fraction'] * 100).round(2).astype(str) + '%'
summary.columns = ['MAE', 'MSE', 'Bias', 'σ_NMAD', 'Outlier %']
summary

                           MAE     MSE    Bias  σ_NMAD Outlier %
model
Linear Regression       0.0712  0.0118  0.0054  0.0500     5.34%
k-Nearest Neighbors     0.0482  0.0080  0.0028  0.0274     2.96%
Random Forest           0.0468  0.0076  0.0019  0.0260     2.98%
XGBoost                 0.0476  0.0078  0.0019  0.0267     3.09%
Multi-Layer Perceptron  0.0503  0.0078 -0.0006  0.0314     3.06%


non-linear models beat linear by a lot

 LR's MSE is 1.5× worse than everything else. the relationship between magnitudes and redshift is clearly non-linear, just as the EDA predicted.

How does MSE compare with the ref paper?


| model | Henghes | ours |
|---|---|---|
| RF | 0.0042 | 0.0076 |
| XGBoost| 0.0043 | 0.0078 |
| kNN | 0.0044 | 0.0080 |
| MLP | 0.0047 | 0.0078 |
| LR | 0.0057 | 0.0118 |



rankings

| rank | Henghes | ours |
|---|---|---|
| 1 | RF | RF |
| 2 | BDT | XGBoost |
| 3 | kNN | MLP |
| 4 | MLP | kNN |
| 5 | LR | LR |

RF wins in both. LR loses in both. the boosted tree comes in second in both. the only swap is MLP vs kNN in the middle - and those two models are within 0.0002 MSE of each other in our results so its not an issue.

pipeline works, model ordering matches Henghes almost exactly. numbers land in expected photo-z ranges, and the gap to Henghes has a clear cause and solution (tuning).



---



---

In [ ]:
import joblib

joblib.dump(knn_search.best_estimator_, 'knn.joblib')